services:
  fastapi:
    build: .
    command: uvicorn api_server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - URL=${URL}
    networks:
      - app_network
    container_name: fastapi

  streamlit:
    build: .
    command: streamlit run streamlit_app.py
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000/ask
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network: # 사용자 정의 네트워크 생성
    driver: bridge
