services:
  fastapi:
    build: .
    command: uvicorn api_server:app --host 0.0.0.0 --port 8000
    ports:
      - "18000:8000"
    env_file:
      - .env.prod  # .env.prod 파일 명시적 참조
    networks:
      - app_network

  streamlit:
    build: .
    command: streamlit run streamlit_app.py
    ports:
      - "18501:8501"
    env_file:
      - .env.prod  # .env.prod 파일 명시적 참조
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network: # 사용자 정의 네트워크 생성
    name: app_network
    driver: bridge
